name: binaural
description: A binaural beat generator using pulse-code modulation.
version: 1.0.0
repository: https://github.com/tytydraco/binaural
publish_to: 'none'

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.3.1

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: any
  wav:
    git: https://github.com/tytydraco/wav
