name: binaural
version: 1.0.0
summary: A binaural beat generator using pulse-code modulation
description: |
  A binaural beat generator using pulse-code modulation.

license: BSD-2-Clause

base: core24
grade: stable
confinement: strict
compression: lzo


apps:
  binaural:
    command: bin/binaural
    plugs:
      - audio-playback
      - home

parts:
  binaural:
    source: https://github.com/tytydraco/binaural
    source-type: git
    plugin: nil
    
    override-build: |
      flutter # prep flutter for build
      dart pub global activate -s git https://github.com/tytydraco/binaural
    
    build-snaps:
      - flutter
