name: binaural
version: 'git'
summary: A binaural beat generator using pulse-code modulation
description: |
  A binaural beat generator using pulse-code modulation.

license: BSD-2-Clause

base: core24
grade: stable
confinement: strict
compression: lzo


apps:
  binaural:
    command: bin/binaural
    plugs:
      - audio-playback
      - home

parts:
  binaural:
    source: https://github.com/tytydraco/binaural
    source-type: git
    plugin: flutter
